// Code generated by mockery v2.53.5. DO NOT EDIT.

package am

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCommandMessageHandler is an autogenerated mock type for the CommandMessageHandler type
type MockCommandMessageHandler[I IncomingMessage] struct {
	mock.Mock
}

type MockCommandMessageHandler_Expecter[I IncomingMessage] struct {
	mock *mock.Mock
}

func (_m *MockCommandMessageHandler[I]) EXPECT() *MockCommandMessageHandler_Expecter[I] {
	return &MockCommandMessageHandler_Expecter[I]{mock: &_m.Mock}
}

// HandleMessage provides a mock function with given fields: ctx, msg
func (_m *MockCommandMessageHandler[I]) HandleMessage(ctx context.Context, msg IncomingCommandMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for HandleMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, IncomingCommandMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommandMessageHandler_HandleMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleMessage'
type MockCommandMessageHandler_HandleMessage_Call[I IncomingMessage] struct {
	*mock.Call
}

// HandleMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg IncomingCommandMessage
func (_e *MockCommandMessageHandler_Expecter[I]) HandleMessage(ctx interface{}, msg interface{}) *MockCommandMessageHandler_HandleMessage_Call[I] {
	return &MockCommandMessageHandler_HandleMessage_Call[I]{Call: _e.mock.On("HandleMessage", ctx, msg)}
}

func (_c *MockCommandMessageHandler_HandleMessage_Call[I]) Run(run func(ctx context.Context, msg IncomingCommandMessage)) *MockCommandMessageHandler_HandleMessage_Call[I] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(IncomingCommandMessage))
	})
	return _c
}

func (_c *MockCommandMessageHandler_HandleMessage_Call[I]) Return(_a0 error) *MockCommandMessageHandler_HandleMessage_Call[I] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommandMessageHandler_HandleMessage_Call[I]) RunAndReturn(run func(context.Context, IncomingCommandMessage) error) *MockCommandMessageHandler_HandleMessage_Call[I] {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandMessageHandler creates a new instance of MockCommandMessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandMessageHandler[I IncomingMessage](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandMessageHandler[I] {
	mock := &MockCommandMessageHandler[I]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
