// Code generated by mockery v2.53.5. DO NOT EDIT.

package am

import mock "github.com/stretchr/testify/mock"

// MockRawMessageSubscriber is an autogenerated mock type for the RawMessageSubscriber type
type MockRawMessageSubscriber[I IncomingMessage] struct {
	mock.Mock
}

type MockRawMessageSubscriber_Expecter[I IncomingMessage] struct {
	mock *mock.Mock
}

func (_m *MockRawMessageSubscriber[I]) EXPECT() *MockRawMessageSubscriber_Expecter[I] {
	return &MockRawMessageSubscriber_Expecter[I]{mock: &_m.Mock}
}

// Subscribe provides a mock function with given fields: topicName, handler, options
func (_m *MockRawMessageSubscriber[I]) Subscribe(topicName string, handler MessageHandler[IncomingRawMessage], options ...SubscriberOption) (Subscription, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, topicName, handler)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(string, MessageHandler[IncomingRawMessage], ...SubscriberOption) (Subscription, error)); ok {
		return rf(topicName, handler, options...)
	}
	if rf, ok := ret.Get(0).(func(string, MessageHandler[IncomingRawMessage], ...SubscriberOption) Subscription); ok {
		r0 = rf(topicName, handler, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(string, MessageHandler[IncomingRawMessage], ...SubscriberOption) error); ok {
		r1 = rf(topicName, handler, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRawMessageSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockRawMessageSubscriber_Subscribe_Call[I IncomingMessage] struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topicName string
//   - handler MessageHandler[IncomingRawMessage]
//   - options ...SubscriberOption
func (_e *MockRawMessageSubscriber_Expecter[I]) Subscribe(topicName interface{}, handler interface{}, options ...interface{}) *MockRawMessageSubscriber_Subscribe_Call[I] {
	return &MockRawMessageSubscriber_Subscribe_Call[I]{Call: _e.mock.On("Subscribe",
		append([]interface{}{topicName, handler}, options...)...)}
}

func (_c *MockRawMessageSubscriber_Subscribe_Call[I]) Run(run func(topicName string, handler MessageHandler[IncomingRawMessage], options ...SubscriberOption)) *MockRawMessageSubscriber_Subscribe_Call[I] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]SubscriberOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(SubscriberOption)
			}
		}
		run(args[0].(string), args[1].(MessageHandler[IncomingRawMessage]), variadicArgs...)
	})
	return _c
}

func (_c *MockRawMessageSubscriber_Subscribe_Call[I]) Return(_a0 Subscription, _a1 error) *MockRawMessageSubscriber_Subscribe_Call[I] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRawMessageSubscriber_Subscribe_Call[I]) RunAndReturn(run func(string, MessageHandler[IncomingRawMessage], ...SubscriberOption) (Subscription, error)) *MockRawMessageSubscriber_Subscribe_Call[I] {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with no fields
func (_m *MockRawMessageSubscriber[I]) Unsubscribe() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRawMessageSubscriber_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockRawMessageSubscriber_Unsubscribe_Call[I IncomingMessage] struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
func (_e *MockRawMessageSubscriber_Expecter[I]) Unsubscribe() *MockRawMessageSubscriber_Unsubscribe_Call[I] {
	return &MockRawMessageSubscriber_Unsubscribe_Call[I]{Call: _e.mock.On("Unsubscribe")}
}

func (_c *MockRawMessageSubscriber_Unsubscribe_Call[I]) Run(run func()) *MockRawMessageSubscriber_Unsubscribe_Call[I] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRawMessageSubscriber_Unsubscribe_Call[I]) Return(_a0 error) *MockRawMessageSubscriber_Unsubscribe_Call[I] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRawMessageSubscriber_Unsubscribe_Call[I]) RunAndReturn(run func() error) *MockRawMessageSubscriber_Unsubscribe_Call[I] {
	_c.Call.Return(run)
	return _c
}

// NewMockRawMessageSubscriber creates a new instance of MockRawMessageSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRawMessageSubscriber[I IncomingMessage](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRawMessageSubscriber[I] {
	mock := &MockRawMessageSubscriber[I]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
