// Code generated by mockery v2.53.5. DO NOT EDIT.

package am

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRawMessageHandler is an autogenerated mock type for the RawMessageHandler type
type MockRawMessageHandler[I IncomingMessage] struct {
	mock.Mock
}

type MockRawMessageHandler_Expecter[I IncomingMessage] struct {
	mock *mock.Mock
}

func (_m *MockRawMessageHandler[I]) EXPECT() *MockRawMessageHandler_Expecter[I] {
	return &MockRawMessageHandler_Expecter[I]{mock: &_m.Mock}
}

// HandleMessage provides a mock function with given fields: ctx, msg
func (_m *MockRawMessageHandler[I]) HandleMessage(ctx context.Context, msg IncomingRawMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for HandleMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, IncomingRawMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRawMessageHandler_HandleMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleMessage'
type MockRawMessageHandler_HandleMessage_Call[I IncomingMessage] struct {
	*mock.Call
}

// HandleMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg IncomingRawMessage
func (_e *MockRawMessageHandler_Expecter[I]) HandleMessage(ctx interface{}, msg interface{}) *MockRawMessageHandler_HandleMessage_Call[I] {
	return &MockRawMessageHandler_HandleMessage_Call[I]{Call: _e.mock.On("HandleMessage", ctx, msg)}
}

func (_c *MockRawMessageHandler_HandleMessage_Call[I]) Run(run func(ctx context.Context, msg IncomingRawMessage)) *MockRawMessageHandler_HandleMessage_Call[I] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(IncomingRawMessage))
	})
	return _c
}

func (_c *MockRawMessageHandler_HandleMessage_Call[I]) Return(_a0 error) *MockRawMessageHandler_HandleMessage_Call[I] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRawMessageHandler_HandleMessage_Call[I]) RunAndReturn(run func(context.Context, IncomingRawMessage) error) *MockRawMessageHandler_HandleMessage_Call[I] {
	_c.Call.Return(run)
	return _c
}

// NewMockRawMessageHandler creates a new instance of MockRawMessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRawMessageHandler[I IncomingMessage](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRawMessageHandler[I] {
	mock := &MockRawMessageHandler[I]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
