// Code generated by mockery v2.53.5. DO NOT EDIT.

package am

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRawMessagePublisher is an autogenerated mock type for the RawMessagePublisher type
type MockRawMessagePublisher[O interface{}] struct {
	mock.Mock
}

type MockRawMessagePublisher_Expecter[O interface{}] struct {
	mock *mock.Mock
}

func (_m *MockRawMessagePublisher[O]) EXPECT() *MockRawMessagePublisher_Expecter[O] {
	return &MockRawMessagePublisher_Expecter[O]{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, topicName, v
func (_m *MockRawMessagePublisher[O]) Publish(ctx context.Context, topicName string, v RawMessage) error {
	ret := _m.Called(ctx, topicName, v)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, RawMessage) error); ok {
		r0 = rf(ctx, topicName, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRawMessagePublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockRawMessagePublisher_Publish_Call[O interface{}] struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topicName string
//   - v RawMessage
func (_e *MockRawMessagePublisher_Expecter[O]) Publish(ctx interface{}, topicName interface{}, v interface{}) *MockRawMessagePublisher_Publish_Call[O] {
	return &MockRawMessagePublisher_Publish_Call[O]{Call: _e.mock.On("Publish", ctx, topicName, v)}
}

func (_c *MockRawMessagePublisher_Publish_Call[O]) Run(run func(ctx context.Context, topicName string, v RawMessage)) *MockRawMessagePublisher_Publish_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(RawMessage))
	})
	return _c
}

func (_c *MockRawMessagePublisher_Publish_Call[O]) Return(_a0 error) *MockRawMessagePublisher_Publish_Call[O] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRawMessagePublisher_Publish_Call[O]) RunAndReturn(run func(context.Context, string, RawMessage) error) *MockRawMessagePublisher_Publish_Call[O] {
	_c.Call.Return(run)
	return _c
}

// NewMockRawMessagePublisher creates a new instance of MockRawMessagePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRawMessagePublisher[O interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRawMessagePublisher[O] {
	mock := &MockRawMessagePublisher[O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
