// Code generated by mockery v2.53.5. DO NOT EDIT.

package am

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMessagePublisher is an autogenerated mock type for the MessagePublisher type
type MockMessagePublisher[O interface{}] struct {
	mock.Mock
}

type MockMessagePublisher_Expecter[O interface{}] struct {
	mock *mock.Mock
}

func (_m *MockMessagePublisher[O]) EXPECT() *MockMessagePublisher_Expecter[O] {
	return &MockMessagePublisher_Expecter[O]{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, topicName, v
func (_m *MockMessagePublisher[O]) Publish(ctx context.Context, topicName string, v O) error {
	ret := _m.Called(ctx, topicName, v)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, O) error); ok {
		r0 = rf(ctx, topicName, v)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessagePublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockMessagePublisher_Publish_Call[O interface{}] struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topicName string
//   - v O
func (_e *MockMessagePublisher_Expecter[O]) Publish(ctx interface{}, topicName interface{}, v interface{}) *MockMessagePublisher_Publish_Call[O] {
	return &MockMessagePublisher_Publish_Call[O]{Call: _e.mock.On("Publish", ctx, topicName, v)}
}

func (_c *MockMessagePublisher_Publish_Call[O]) Run(run func(ctx context.Context, topicName string, v O)) *MockMessagePublisher_Publish_Call[O] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(O))
	})
	return _c
}

func (_c *MockMessagePublisher_Publish_Call[O]) Return(_a0 error) *MockMessagePublisher_Publish_Call[O] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessagePublisher_Publish_Call[O]) RunAndReturn(run func(context.Context, string, O) error) *MockMessagePublisher_Publish_Call[O] {
	_c.Call.Return(run)
	return _c
}

// NewMockMessagePublisher creates a new instance of MockMessagePublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessagePublisher[O interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessagePublisher[O] {
	mock := &MockMessagePublisher[O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
