// Code generated by mockery v2.53.5. DO NOT EDIT.

package application

import (
	context "context"
	commands "eda-in-golang/depot/internal/application/commands"

	domain "eda-in-golang/depot/internal/domain"

	mock "github.com/stretchr/testify/mock"

	queries "eda-in-golang/depot/internal/application/queries"
)

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

type MockApp_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApp) EXPECT() *MockApp_Expecter {
	return &MockApp_Expecter{mock: &_m.Mock}
}

// AssignShoppingList provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AssignShoppingList(ctx context.Context, cmd commands.AssignShoppingList) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AssignShoppingList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AssignShoppingList) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_AssignShoppingList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignShoppingList'
type MockApp_AssignShoppingList_Call struct {
	*mock.Call
}

// AssignShoppingList is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.AssignShoppingList
func (_e *MockApp_Expecter) AssignShoppingList(ctx interface{}, cmd interface{}) *MockApp_AssignShoppingList_Call {
	return &MockApp_AssignShoppingList_Call{Call: _e.mock.On("AssignShoppingList", ctx, cmd)}
}

func (_c *MockApp_AssignShoppingList_Call) Run(run func(ctx context.Context, cmd commands.AssignShoppingList)) *MockApp_AssignShoppingList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.AssignShoppingList))
	})
	return _c
}

func (_c *MockApp_AssignShoppingList_Call) Return(_a0 error) *MockApp_AssignShoppingList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_AssignShoppingList_Call) RunAndReturn(run func(context.Context, commands.AssignShoppingList) error) *MockApp_AssignShoppingList_Call {
	_c.Call.Return(run)
	return _c
}

// CancelShoppingList provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CancelShoppingList(ctx context.Context, cmd commands.CancelShoppingList) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CancelShoppingList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CancelShoppingList) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_CancelShoppingList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelShoppingList'
type MockApp_CancelShoppingList_Call struct {
	*mock.Call
}

// CancelShoppingList is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.CancelShoppingList
func (_e *MockApp_Expecter) CancelShoppingList(ctx interface{}, cmd interface{}) *MockApp_CancelShoppingList_Call {
	return &MockApp_CancelShoppingList_Call{Call: _e.mock.On("CancelShoppingList", ctx, cmd)}
}

func (_c *MockApp_CancelShoppingList_Call) Run(run func(ctx context.Context, cmd commands.CancelShoppingList)) *MockApp_CancelShoppingList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.CancelShoppingList))
	})
	return _c
}

func (_c *MockApp_CancelShoppingList_Call) Return(_a0 error) *MockApp_CancelShoppingList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_CancelShoppingList_Call) RunAndReturn(run func(context.Context, commands.CancelShoppingList) error) *MockApp_CancelShoppingList_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteShoppingList provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CompleteShoppingList(ctx context.Context, cmd commands.CompleteShoppingList) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CompleteShoppingList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CompleteShoppingList) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_CompleteShoppingList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteShoppingList'
type MockApp_CompleteShoppingList_Call struct {
	*mock.Call
}

// CompleteShoppingList is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.CompleteShoppingList
func (_e *MockApp_Expecter) CompleteShoppingList(ctx interface{}, cmd interface{}) *MockApp_CompleteShoppingList_Call {
	return &MockApp_CompleteShoppingList_Call{Call: _e.mock.On("CompleteShoppingList", ctx, cmd)}
}

func (_c *MockApp_CompleteShoppingList_Call) Run(run func(ctx context.Context, cmd commands.CompleteShoppingList)) *MockApp_CompleteShoppingList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.CompleteShoppingList))
	})
	return _c
}

func (_c *MockApp_CompleteShoppingList_Call) Return(_a0 error) *MockApp_CompleteShoppingList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_CompleteShoppingList_Call) RunAndReturn(run func(context.Context, commands.CompleteShoppingList) error) *MockApp_CompleteShoppingList_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShoppingList provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CreateShoppingList(ctx context.Context, cmd commands.CreateShoppingList) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateShoppingList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateShoppingList) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_CreateShoppingList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShoppingList'
type MockApp_CreateShoppingList_Call struct {
	*mock.Call
}

// CreateShoppingList is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.CreateShoppingList
func (_e *MockApp_Expecter) CreateShoppingList(ctx interface{}, cmd interface{}) *MockApp_CreateShoppingList_Call {
	return &MockApp_CreateShoppingList_Call{Call: _e.mock.On("CreateShoppingList", ctx, cmd)}
}

func (_c *MockApp_CreateShoppingList_Call) Run(run func(ctx context.Context, cmd commands.CreateShoppingList)) *MockApp_CreateShoppingList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.CreateShoppingList))
	})
	return _c
}

func (_c *MockApp_CreateShoppingList_Call) Return(_a0 error) *MockApp_CreateShoppingList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_CreateShoppingList_Call) RunAndReturn(run func(context.Context, commands.CreateShoppingList) error) *MockApp_CreateShoppingList_Call {
	_c.Call.Return(run)
	return _c
}

// GetShoppingList provides a mock function with given fields: ctx, query
func (_m *MockApp) GetShoppingList(ctx context.Context, query queries.GetShoppingList) (*domain.ShoppingList, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetShoppingList")
	}

	var r0 *domain.ShoppingList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetShoppingList) (*domain.ShoppingList, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetShoppingList) *domain.ShoppingList); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ShoppingList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetShoppingList) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_GetShoppingList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShoppingList'
type MockApp_GetShoppingList_Call struct {
	*mock.Call
}

// GetShoppingList is a helper method to define mock.On call
//   - ctx context.Context
//   - query queries.GetShoppingList
func (_e *MockApp_Expecter) GetShoppingList(ctx interface{}, query interface{}) *MockApp_GetShoppingList_Call {
	return &MockApp_GetShoppingList_Call{Call: _e.mock.On("GetShoppingList", ctx, query)}
}

func (_c *MockApp_GetShoppingList_Call) Run(run func(ctx context.Context, query queries.GetShoppingList)) *MockApp_GetShoppingList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.GetShoppingList))
	})
	return _c
}

func (_c *MockApp_GetShoppingList_Call) Return(_a0 *domain.ShoppingList, _a1 error) *MockApp_GetShoppingList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_GetShoppingList_Call) RunAndReturn(run func(context.Context, queries.GetShoppingList) (*domain.ShoppingList, error)) *MockApp_GetShoppingList_Call {
	_c.Call.Return(run)
	return _c
}

// InitiateShopping provides a mock function with given fields: ctx, cmd
func (_m *MockApp) InitiateShopping(ctx context.Context, cmd commands.InitiateShopping) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for InitiateShopping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.InitiateShopping) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_InitiateShopping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiateShopping'
type MockApp_InitiateShopping_Call struct {
	*mock.Call
}

// InitiateShopping is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.InitiateShopping
func (_e *MockApp_Expecter) InitiateShopping(ctx interface{}, cmd interface{}) *MockApp_InitiateShopping_Call {
	return &MockApp_InitiateShopping_Call{Call: _e.mock.On("InitiateShopping", ctx, cmd)}
}

func (_c *MockApp_InitiateShopping_Call) Run(run func(ctx context.Context, cmd commands.InitiateShopping)) *MockApp_InitiateShopping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.InitiateShopping))
	})
	return _c
}

func (_c *MockApp_InitiateShopping_Call) Return(_a0 error) *MockApp_InitiateShopping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_InitiateShopping_Call) RunAndReturn(run func(context.Context, commands.InitiateShopping) error) *MockApp_InitiateShopping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApp creates a new instance of MockApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApp {
	mock := &MockApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
