// Code generated by mockery v2.53.5. DO NOT EDIT.

package application

import (
	context "context"
	commands "eda-in-golang/depot/internal/application/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockCommands is an autogenerated mock type for the Commands type
type MockCommands struct {
	mock.Mock
}

type MockCommands_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommands) EXPECT() *MockCommands_Expecter {
	return &MockCommands_Expecter{mock: &_m.Mock}
}

// AssignShoppingList provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) AssignShoppingList(ctx context.Context, cmd commands.AssignShoppingList) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AssignShoppingList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AssignShoppingList) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_AssignShoppingList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignShoppingList'
type MockCommands_AssignShoppingList_Call struct {
	*mock.Call
}

// AssignShoppingList is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.AssignShoppingList
func (_e *MockCommands_Expecter) AssignShoppingList(ctx interface{}, cmd interface{}) *MockCommands_AssignShoppingList_Call {
	return &MockCommands_AssignShoppingList_Call{Call: _e.mock.On("AssignShoppingList", ctx, cmd)}
}

func (_c *MockCommands_AssignShoppingList_Call) Run(run func(ctx context.Context, cmd commands.AssignShoppingList)) *MockCommands_AssignShoppingList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.AssignShoppingList))
	})
	return _c
}

func (_c *MockCommands_AssignShoppingList_Call) Return(_a0 error) *MockCommands_AssignShoppingList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_AssignShoppingList_Call) RunAndReturn(run func(context.Context, commands.AssignShoppingList) error) *MockCommands_AssignShoppingList_Call {
	_c.Call.Return(run)
	return _c
}

// CancelShoppingList provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CancelShoppingList(ctx context.Context, cmd commands.CancelShoppingList) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CancelShoppingList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CancelShoppingList) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_CancelShoppingList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelShoppingList'
type MockCommands_CancelShoppingList_Call struct {
	*mock.Call
}

// CancelShoppingList is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.CancelShoppingList
func (_e *MockCommands_Expecter) CancelShoppingList(ctx interface{}, cmd interface{}) *MockCommands_CancelShoppingList_Call {
	return &MockCommands_CancelShoppingList_Call{Call: _e.mock.On("CancelShoppingList", ctx, cmd)}
}

func (_c *MockCommands_CancelShoppingList_Call) Run(run func(ctx context.Context, cmd commands.CancelShoppingList)) *MockCommands_CancelShoppingList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.CancelShoppingList))
	})
	return _c
}

func (_c *MockCommands_CancelShoppingList_Call) Return(_a0 error) *MockCommands_CancelShoppingList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_CancelShoppingList_Call) RunAndReturn(run func(context.Context, commands.CancelShoppingList) error) *MockCommands_CancelShoppingList_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteShoppingList provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CompleteShoppingList(ctx context.Context, cmd commands.CompleteShoppingList) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CompleteShoppingList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CompleteShoppingList) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_CompleteShoppingList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteShoppingList'
type MockCommands_CompleteShoppingList_Call struct {
	*mock.Call
}

// CompleteShoppingList is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.CompleteShoppingList
func (_e *MockCommands_Expecter) CompleteShoppingList(ctx interface{}, cmd interface{}) *MockCommands_CompleteShoppingList_Call {
	return &MockCommands_CompleteShoppingList_Call{Call: _e.mock.On("CompleteShoppingList", ctx, cmd)}
}

func (_c *MockCommands_CompleteShoppingList_Call) Run(run func(ctx context.Context, cmd commands.CompleteShoppingList)) *MockCommands_CompleteShoppingList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.CompleteShoppingList))
	})
	return _c
}

func (_c *MockCommands_CompleteShoppingList_Call) Return(_a0 error) *MockCommands_CompleteShoppingList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_CompleteShoppingList_Call) RunAndReturn(run func(context.Context, commands.CompleteShoppingList) error) *MockCommands_CompleteShoppingList_Call {
	_c.Call.Return(run)
	return _c
}

// CreateShoppingList provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CreateShoppingList(ctx context.Context, cmd commands.CreateShoppingList) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateShoppingList")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateShoppingList) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_CreateShoppingList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateShoppingList'
type MockCommands_CreateShoppingList_Call struct {
	*mock.Call
}

// CreateShoppingList is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.CreateShoppingList
func (_e *MockCommands_Expecter) CreateShoppingList(ctx interface{}, cmd interface{}) *MockCommands_CreateShoppingList_Call {
	return &MockCommands_CreateShoppingList_Call{Call: _e.mock.On("CreateShoppingList", ctx, cmd)}
}

func (_c *MockCommands_CreateShoppingList_Call) Run(run func(ctx context.Context, cmd commands.CreateShoppingList)) *MockCommands_CreateShoppingList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.CreateShoppingList))
	})
	return _c
}

func (_c *MockCommands_CreateShoppingList_Call) Return(_a0 error) *MockCommands_CreateShoppingList_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_CreateShoppingList_Call) RunAndReturn(run func(context.Context, commands.CreateShoppingList) error) *MockCommands_CreateShoppingList_Call {
	_c.Call.Return(run)
	return _c
}

// InitiateShopping provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) InitiateShopping(ctx context.Context, cmd commands.InitiateShopping) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for InitiateShopping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.InitiateShopping) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_InitiateShopping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitiateShopping'
type MockCommands_InitiateShopping_Call struct {
	*mock.Call
}

// InitiateShopping is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.InitiateShopping
func (_e *MockCommands_Expecter) InitiateShopping(ctx interface{}, cmd interface{}) *MockCommands_InitiateShopping_Call {
	return &MockCommands_InitiateShopping_Call{Call: _e.mock.On("InitiateShopping", ctx, cmd)}
}

func (_c *MockCommands_InitiateShopping_Call) Run(run func(ctx context.Context, cmd commands.InitiateShopping)) *MockCommands_InitiateShopping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.InitiateShopping))
	})
	return _c
}

func (_c *MockCommands_InitiateShopping_Call) Return(_a0 error) *MockCommands_InitiateShopping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_InitiateShopping_Call) RunAndReturn(run func(context.Context, commands.InitiateShopping) error) *MockCommands_InitiateShopping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommands creates a new instance of MockCommands. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommands(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommands {
	mock := &MockCommands{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
