// Code generated by mockery v2.53.5. DO NOT EDIT.

package application

import (
	context "context"
	domain "eda-in-golang/depot/internal/domain"

	mock "github.com/stretchr/testify/mock"

	queries "eda-in-golang/depot/internal/application/queries"
)

// MockQueries is an autogenerated mock type for the Queries type
type MockQueries struct {
	mock.Mock
}

type MockQueries_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueries) EXPECT() *MockQueries_Expecter {
	return &MockQueries_Expecter{mock: &_m.Mock}
}

// GetShoppingList provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetShoppingList(ctx context.Context, query queries.GetShoppingList) (*domain.ShoppingList, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetShoppingList")
	}

	var r0 *domain.ShoppingList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetShoppingList) (*domain.ShoppingList, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetShoppingList) *domain.ShoppingList); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ShoppingList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetShoppingList) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueries_GetShoppingList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShoppingList'
type MockQueries_GetShoppingList_Call struct {
	*mock.Call
}

// GetShoppingList is a helper method to define mock.On call
//   - ctx context.Context
//   - query queries.GetShoppingList
func (_e *MockQueries_Expecter) GetShoppingList(ctx interface{}, query interface{}) *MockQueries_GetShoppingList_Call {
	return &MockQueries_GetShoppingList_Call{Call: _e.mock.On("GetShoppingList", ctx, query)}
}

func (_c *MockQueries_GetShoppingList_Call) Run(run func(ctx context.Context, query queries.GetShoppingList)) *MockQueries_GetShoppingList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.GetShoppingList))
	})
	return _c
}

func (_c *MockQueries_GetShoppingList_Call) Return(_a0 *domain.ShoppingList, _a1 error) *MockQueries_GetShoppingList_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueries_GetShoppingList_Call) RunAndReturn(run func(context.Context, queries.GetShoppingList) (*domain.ShoppingList, error)) *MockQueries_GetShoppingList_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueries creates a new instance of MockQueries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueries(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueries {
	mock := &MockQueries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
